使用Python实现了分割样本的函数sample_split

In [1]:
import random
import numpy as np

def sample_split(df, k):
    """
    本函数实现对样本的分割
    df:数据框对象
    k:分割数量
    return:返回类别数组
    """
    t0 = np.array(range(df.shape[0]))%k
    random.shuffle(t0)
    return t0

这里使用iris数据集，并建立Sepal.Length、Sepal.Width、Petal.Length对Petal.Width的线性回归模型

In [2]:
import pandas as pd
from sklearn import linear_model 

iris = pd.read_csv("http://image.cador.cn/data/iris.csv")
X = iris.loc[:,['Sepal.Length','Sepal.Width','Petal.Length']]
y = iris.loc[:,['Petal.Width']]

# 设置为10折交叉验证
k=10
parts = sample_split(iris, k)

# 初始化最小均方误差 min_error
min_error = 1000

# 初始化最佳拟合结果 finalfit
final_fit = None

for i in range(k):
    reg = linear_model.LinearRegression()
    X_train = X.iloc[parts!=i,:]
    y_train = y.iloc[parts!=i,:]
    X_test = X.iloc[parts==i,:]
    y_test = y.iloc[parts==i,:]
    # 拟合线性回归模型
    reg.fit(X_train, y_train)
    # 计算均方误差
    error = np.mean((y_test.values - reg.predict(X_test))**2)
    if error < min_error:
        min_error = error
        final_fit = reg

min_error
# 0.014153864387035597

final_fit.coef_
# array([[-0.20013407,  0.21165518,  0.51669477]])

# 2、使用一般方法得到的参数
reg = linear_model.LinearRegression()
reg.fit(X, y)
reg.coef_
# array([[-0.20726607,  0.22282854,  0.52408311]])

array([[-0.20726607,  0.22282854,  0.52408311]])